### ISSUE TITLE
Server RDT causes node --watch to hang

### ISSUE THREAD

**Issue by xHomu** [Code-Forge-Net/Remix-Dev-Tools#61] opened 2023-10-09 22:17 UTC
Installing the Server RDT cause node --watch to hang at "Waiting for graceful termination..." when restarting.

## Steps to reproduce

1. https://github.com/xHomu/rdt-node-watch
2. npm install; npm run dev
3. Make any changes to `server.js`.

## Expectations

If we remove server RDT, (revert to this commit https://github.com/xHomu/rdt-node-watch/commit/88e86daf3d791a965b5292eafbcde792e32cd2b2), then the Express server restarts as expected.

**Comment by AlemTuzlak** [comment] 2023-10-10 07:33
will check this out very soon, I think I know the root cause

**Comment by AlemTuzlak** [comment] 2023-12-01 13:31
@xHomu this won't be an issue on Vite, I won't be fixing this because I plan to drop completely the code that makes this issue in the first place

**Closed by AlemTuzlak** 2023-12-01 13:31 UTC
